### ISSUE TITLE
Feature request: Ability to hide non-user written methods

### ISSUE THREAD

**Issue by quantum-booty** [ldelossa/calltree.nvim#16]
Right now its difficult to distinguish methods from external packages vs methods written by the user. It would be nice to indicate or have the ability to hide external methods. I can imagine that users more often than not, would like to see the calltree of users written methods. For example in the below calltree, I only care about the pad_grid and count_active_neighbours calls, and not the external dependencies circled in red.
![image](https://user-images.githubusercontent.com/28958399/143044872-cb4ae6c4-2f11-424e-bbad-3c48f9cbded1.png)

**Comment by ldelossa** [comment]
Can you elaborate?

**Comment by quantum-booty** [comment]
Sorry I've updated the description.

**Comment by ldelossa** [comment]
@quantum-booty I actually just pushed a change which adjusts the UI quite a bit. Can you update the plugin and try it then provide feedback? The change now shows the file's path returned from LSP. 

The UI now looks like this

![image](https://user-images.githubusercontent.com/5642902/143058674-bca24d3d-6a7c-425a-97a3-8b36ac2dc7a8.png)

I'd have to think about if excluding external methods/functions could happen. Since an external function could still be another package in your workspace.

**Comment by quantum-booty** [comment]
@ldelossa is it possible to print the package name only? The paths can get pretty long and hard to read.
![image](https://user-images.githubusercontent.com/28958399/143082688-1ef51605-fa8b-4f7b-8859-29db3ded95d5.png)

**Comment by ldelossa** [comment]
yikes, we definitely don't want that. 

Here is what VSCode displays when having two internal symbols, and one external: 

![image](https://user-images.githubusercontent.com/5642902/143086197-256e6e7d-6697-4437-9d20-956f08a96718.png)

The thing is, I do not like having those long package paths for *local* symbols, I'd rather just have the file since you can navigate to it easily. 

What I'm thinking is a combination of what VSCode does and what I do. 

If the symbol belongs to a file which is local in your workspace, we'll just display the relative path to the file. 

If we cannot resolve a relative path to the file like in the above case, we'll only show the package/filename details.

**Comment by ldelossa** [comment]
@quantum-booty I merged the above mentioned logic. Let me know your feedback.

**Comment by quantum-booty** [comment]
> @quantum-booty I merged the above mentioned logic. Let me know your feedback.

Unfortunately Pyright language server doesn't seem to provide "detail" field.
![image](https://user-images.githubusercontent.com/28958399/143300778-0673e773-169c-4cc3-98a9-b908caa6995e.png)
I still think it would be nice to be able to toggle the visibility of external functions. Maybe mapped to key "."

**Comment by ldelossa** [comment]
@quantum-booty can you actually do a "print(vim.inspect())" on the call_hierarchy_item table there? Want to see what LSP is giving you back.

**Comment by quantum-booty** [comment]
@ldelossa 
Here is print(vim.inspect(node))
```json
{
  call_hierarchy_item = {
    kind = 12,
    name = "print",
    range = {
      end = {
        character = 9,
        line = 1250
      },
      start = {
        character = 4,
        line = 1250
      }
    },
    selectionRange = {
      end = {
        character = 9,
        line = 1250
      },
      start = {
        character = 4,
        line = 1250
      }
    },
    uri = "file:///usr/lib/node_modules/pyright/dist/typeshed-fallback/stdlib/builtins.pyi"
  },
  children = {},
  depth = 1,
  expanded = false,
  key = "print:file:///usr/lib/node_modules/pyright/dist/typeshed-fallback/stdlib/builtins.pyi:1250",
  name = "print",
  references = { {
      end = {
        character = 13,
        line = 258
      },
      start = {
        character = 8,
        line = 258
      }
    } },
  uri = ""
}
{
  kind = 12,
  name = "print",
  range = {
    end = {
      character = 9,
      line = 1250
    },
    start = {
      character = 4,
      line = 1250
    }
  },
  selectionRange = {
    end = {
      character = 9,
      line = 1250
    },
    start = {
      character = 4,
      line = 1250
    }
  },
  uri = "file:///usr/lib/node_modules/pyright/dist/typeshed-fallback/stdlib/builtins.pyi"
}

```

**Comment by ldelossa** [comment]
@quantum-booty i'm a little hesitant to hide the external symbols, as I don't see other IDE's doing this. 

I installed pyright in vscode and looked up an external symbol. It shows the entry but just leaves out any file information:

![image](https://user-images.githubusercontent.com/5642902/143309608-40bd2c29-5484-479b-81dd-0d5a04cc070f.png)


I think I will just do this. If someone *does* want to know where that external file is on the file system they can press "d" key on the symbol for the details popup.

**Comment by ldelossa** [comment]
@quantum-booty logic above implemented. give it a try and provide feedback.

**Comment by quantum-booty** [comment]
> @quantum-booty logic above implemented. give it a try and provide feedback.

It looks very nice! Thanks a lot for this feature!
